In [ ]:
import pandas as pd

df = pd.read_csv("data_for_embeddings_part_1.csv")

In [ ]:
df = df['text']

In [ ]:
df.shape

(10000,)

In [ ]:
df = df.to_frame()
df.shape

(10000, 1)

In [ ]:
import pandas as pd

# Function to split text into sentences based on period (.)
def split_into_sentences(text):
    # Split by period and remove leading/trailing spaces from each sentence
    sentences = [sentence.strip() for sentence in text.split('.') if sentence]
    return sentences

# Apply function to the 'text' column and explode the list into separate rows
df_sentences = df['text'].apply(split_into_sentences).explode().reset_index(drop=True)

# Create new DataFrame with the sentences
df_sentences = pd.DataFrame({'sentence': df_sentences})

# Show the new DataFrame
df_sentences.head()

                                                                                                                                                                           sentence
0                                                                                                                                                      OPINION\nRABINOWITZ, Justice
1                                                                                                                                                                                 I
2  INTRODUCTION\nThis appeal centers on the application of the notice requirement of the Differing Site Conditions clause found in a contract between appellant Neal & Company, Inc
3                                                                                                                                      (NCI) and appellee City of Dillingham (City)
4                 Ap-pellee CH2M Hill (Hill), the City's engineer on the project, is involved in this appeal primarily because it acted as the City's representative on the project

In [ ]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
pd.set_option('display.max_colwidth', None)

df_sentences.head(50)

                                                                                                                                                                                                                                                                                                                sentence
0                                                                                                                                                                                                                                                                                           OPINION\nRABINOWITZ, Justice
1                                                                                                                                                                                                                                                                                                                      I
2                                                                                                                                       INTRODUCTION\nThis appeal centers on the application of the notice requirement of the Differing Site Conditions clause found in a contract between appellant Neal & Company, Inc
3                                                                                                                                                                                                                                                                           (NCI) and appellee City of Dillingham (City)
4                                                                                                                                                      Ap-pellee CH2M Hill (Hill), the City's engineer on the project, is involved in this appeal primarily because it acted as the City's representative on the project
5   NCI claims that it encountered difficulties in excavation during the project because of unexpected soil conditions, that it gave notice of these unexpected conditions to Hill (and thus constructively to the City), and that therefore it is entitled to assert a claim under the Differing Site Conditions clause
6                                                                                                                                                                                                                                         The City and Hill claim that no notice of a differing site condition was given
7                                                                                                                                                                                               The superior court ruled on partial summary judgment that NCI did not give adequate notice of a differing site condition
8                                                                                                                                                NCI also appeals the superior court's denial of its motions for leave to amend its complaint, for continuance of the trial, and for disqualification of thé trial judge
9                                                                                                                                                                                                                                                                                                                     II
10                                                                                                                                                                                                                           FACTS\nIn February 1987 the City solicited bids for the construction of a sewerage facility
11                                                                                                                                                                                                                                                                                 The project included two lagoon ponds
12                                                                                                                                                                                                                                                         The lagoons were to be dug into a bluff outside of Dillingham
13                                                                                                      Interested bidders received a set of drawings and a volume containing bidding requirements, contract forms, conditions of the contract, and construction specifications, along with a "Geotechnical Data Summary
14                                                                                                                         " The geological survey and the data summary, as well as all technical specifications for the project, were completed by Hill, the City's engineer and on-site representative for the project
15                                                                                                                                                                       The first dig in the construction of the lagoons was to be a wedge-cut into the bluff from the surface down to an elevation of forty-seven feet
16                                                                                                                                        After the first dig down to the forty-seven foot level, the second dig would begin, consisting of the excavation of two ponds down from the flat area created by the first dig
17                                                                                                                                                                                                              The pools were to be eighteen feet deep, reaching an elevation of twenty-nine feet at their lowest point
18                                                                                                                                                             The data summary stated that there was a layer of peat containing some silt infilling extending four feet to eight feet below the original ground surface
19                                                                                                                                                                              Below the peat was a layer of sand and silty sand interbedded with layers of silt extending about six to twelve feet below the peat zone
20                                                                                                          Below that, the data summary described the remaining depth of the excavation as "fairly uniform to the remaining depth of the borings, showing a layer of stiff-to-hard clay having low-to-medium plasticity
21                                                                                                                     " Regarding the clay layer, the data summary specified: "Occasional samples contained clay with gravel and sand suspended in the clay matrix, indicating that the clay unit may be a glacial till
22                                                                                                                                                                                                                                  No distinct bedding or layers of coarse grained material were found in the clay unit
23                                                                                      " The data summary went on to describe the process by which the lagoons could be constructed:\nThe most attractive aspect of constructing the lagoons in the lower clay zone of the bluff is that they will not have to be lined
24                                                                                                                             Also, native materials will not have to be recompacted to form the dikes, as the dikes can be constructed by carving the lagoons out of the bluff and leaving the clay intact around them
25                                                                                                                                                                        Construction concerns for this configuration are primarily slope protection against seepage and removal and disposal of the excavated material
26                                                                                                                                                                                                                                                                           A set of contract documents was sent to NCI
27                                                                                                                                                                                                                                  On April 1,1987, bids were opened and NCI was declared the low bidder at $2,059,-991
28                                                                                                                                                                                                                                                                              NCI began the excavation on June 6, 1987
29                                                                                                                                                                                                                Excavation of the first dig, down to the forty-seven foot elevation of the pond surface, was completed
30                                                                                                                                                                                                                                                                                    Work was suspended in October 1987
31                                                                                                                                                                                                                                            The second dig, excavation of the pond prisms, began when the ground froze
32                                                                                                                                                                                                                                                                             Excavation was completed by April 20,1988
33                                                                                                                                                                                       During the summer of 1987, while excavating the first dig, NCI encountered water bubbling through sand lenses in the excavation
34                                                                                                    Randy Mattoon, NCI's project superintendent, discussed with Tony Neal, president of NCI, the possibility of the existence of sand lenses impairing the integrity of the lagoon, which would allow sewage to escape
35                                                                                                                                                                                                                Mattoon also discussed the issue of water permeable sand lenses with Bob Richie, Hill's representative
36                                                                                                                                                                                                                  Ken Green, a Hill geotechnical engineer, was scheduled to visit the project the week of July 27,1987
37                                                                                                                                                                                          NCI contends that Green's visit was scheduled after and because of the Mattoon-Riehie conversation regarding the sand lenses
38                                                                                                                                                                                                                                               The City and Hill contend that Green's visit had already been scheduled
39                                                                                                                                                                                                 During Green's visit, a test pit was dug in each of the pond prisms, and a soil sample was taken from one of the pits
40                                                                                                     Green's field notes, taken at the time the pits were dug, indicate that at the level where the lagoons were to be dug, he saw "clayey silt Slightly plastic Blue Gray Moist slightly Blocky structure, stiff to n
41                                                                                                                                                                                                                                                                                                                stiff[
42                                                                                                   ]" This level (two to nineteen feet down from the forty-seven foot elevation of the surface of the lagoon) had been described in the Data Summary as "a layer of stiff-to-hard clay having low-to-medium plasticity
43                                                                                                                                                                                                                         "\nDuring this time, the consistency of the soil was causing difficulties in NCI's excavation
44                                                                                                                                                                                                            The soil in the lagoon area turned into a sticky mud, creating problems with excavation and transportation
45                                                                                                                                                                                              The consistency of the soil, and the difficulty of excavating it, form the basis of NCI's Differing Site Condition claim
46                                                                                                                                                                                                                               During the 1988 phase of the excavation, water infiltration continued to cause problems
47                                                                                                                                                                                                                                                In October 1988, NCI advised Hill that it was considering legal action
48                                                                                                                                                                                                                                                                                                   NCI then filed suit
49                                                                                                                                                                                                                                                                                                                   III

In [ ]:
df_sentences.shape

(2731607, 1)

In [ ]:
import random
import pandas as pd

# Assuming df_sentences is your DataFrame with shape (1000, 1)
# and df_sentences['sentences'] contains the sentences.

def mask_sentence(sentence, mask_prob=0.1):
    words = sentence.split()  # Split sentence into words
    masked_words = []

    for word in words:
        if random.random() < mask_prob:  # 10% chance to mask the word
            masked_words.append("[MASK]")
        else:
            masked_words.append(word)

    return " ".join(masked_words)  # Join words back into a sentence

# Apply the masking function to each sentence in the DataFrame
df_sentences['masked_sentences'] = df_sentences['sentence'].apply(mask_sentence)

# Now df_sentences contains the original sentences and the masked versions

In [ ]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
pd.set_option('display.max_colwidth', None)

df_sentences.head(50)

,sentence,masked_sentences
0,"OPINION\nRABINOWITZ, Justice",OPINION [MASK] [MASK]
1,I,I
2,"INTRODUCTION\nThis appeal centers on the application of the notice requirement of the Differing Site Conditions clause found in a contract between appellant Neal & Company, Inc","INTRODUCTION This appeal centers on the application of the notice requirement of the [MASK] Site [MASK] clause found in a contract [MASK] appellant Neal & Company, Inc"
3,(NCI) and appellee City of Dillingham (City),(NCI) and appellee City of Dillingham (City)
4,"Ap-pellee CH2M Hill (Hill), the City's engineer on the project, is involved in this appeal primarily because it acted as the City's representative on the project","Ap-pellee CH2M Hill (Hill), the City's engineer on the project, [MASK] involved in this appeal primarily because it [MASK] as the City's representative on [MASK] project"
5,"NCI claims that it encountered difficulties in excavation during the project because of unexpected soil conditions, that it gave notice of these unexpected conditions to Hill (and thus constructively to the City), and that therefore it is entitled to assert a claim under the Differing Site Conditions clause","NCI claims [MASK] it encountered difficulties in excavation [MASK] the project because of unexpected soil conditions, that it gave notice of these [MASK] conditions to Hill [MASK] thus constructively to the City), and that therefore it is entitled to assert a [MASK] under the [MASK] Site Conditions clause"
6,The City and Hill claim that no notice of a differing site condition was given,The [MASK] [MASK] Hill claim that no notice of a differing site condition was given
7,The superior court ruled on partial summary judgment that NCI did not give adequate notice of a differing site condition,The superior court ruled on partial summary judgment that NCI did not give adequate notice of a differing site condition
8,"NCI also appeals the superior court's denial of its motions for leave to amend its complaint, for continuance of the trial, and for disqualification of thé trial judge","NCI also appeals the superior court's denial of its motions for leave to amend its complaint, for continuance of the trial, and for disqualification of thé trial judge"
9,II,II
10,FACTS\nIn February 1987 the City solicited bids for the construction of a sewerage facility,FACTS In February [MASK] the [MASK] solicited bids for the construction of a sewerage facility
11,The project included two lagoon ponds,[MASK] project included two lagoon ponds
12,The lagoons were to be dug into a bluff outside of Dillingham,The lagoons were to be dug into a bluff outside of Dillingham
13,"Interested bidders received a set of drawings and a volume containing bidding requirements, contract forms, conditions of the contract, and construction specifications, along with a ""Geotechnical Data Summary","Interested [MASK] received a set of drawings [MASK] a volume containing bidding requirements, contract forms, conditions of the contract, and construction specifications, along with a ""Geotechnical Data Summary"
14,""" The geological survey and the data summary, as well as all technical specifications for the project, were completed by Hill, the City's engineer and on-site representative for the project",""" The geological survey and the [MASK] summary, as well as all technical [MASK] for the project, were completed by [MASK] the [MASK] engineer and on-site representative for the project"
15,The first dig in the construction of the lagoons was to be a wedge-cut into the bluff from the surface down to an elevation of forty-seven feet,[MASK] first dig in the construction of the [MASK] [MASK] to [MASK] a wedge-cut into the bluff from the [MASK] down to an elevation [MASK] forty-seven feet
16,"After the first dig down to the forty-seven foot level, the second dig would begin, consisting of the excavation of two ponds down from the flat area created by the first dig","After the first dig down to the forty-seven foot level, the second dig would begin, consisting of the excavation of [MASK] ponds down from the flat [MASK] created by [MASK] [MASK] dig"
17,"The pools were to be eighteen feet deep, reaching an elevation of twenty-nine feet at their lowest point","The pools [MASK] to be [MASK] feet deep, reaching [MASK] elevation of twenty-nine feet at their lowest point"
18,The data summary stated that there was a layer of peat containing some silt infilling extending four feet to eight feet below the original ground surface,The data summary [MASK] [MASK] there was a layer of [MASK] containing some silt infilling extending four feet to eight [MASK] below the original ground surface
19,Below the peat was a layer of sand and silty sand interbedded with layers of silt extending about six to twelve feet below the peat zone,Below [MASK] peat was a layer of sand [MASK] silty sand [MASK] with layers of silt extending about six to twelve feet below the peat zone
20,"Below that, the data summary described the remaining depth of the excavation as ""fairly uniform to the remaining depth of the borings, showing a layer of stiff-to-hard clay having low-to-medium plasticity","Below that, [MASK] data summary described the remaining depth of the excavation as ""fairly uniform to the remaining depth of the [MASK] showing a layer of stiff-to-hard clay having low-to-medium plasticity"
21,""" Regarding the clay layer, the data summary specified: ""Occasional samples contained clay with gravel and sand suspended in the clay matrix, indicating that the clay unit may be a glacial till",""" [MASK] the clay layer, the data summary specified: [MASK] samples contained clay with gravel and sand suspended in the clay matrix, indicating that the clay unit may be a glacial till"
22,No distinct bedding or layers of coarse grained material were found in the clay unit,No distinct bedding or layers of coarse grained material [MASK] found in the clay unit
23,""" The data summary went on to describe the process by which the lagoons could be constructed:\nThe most attractive aspect of constructing the lagoons in the lower clay zone of the bluff is that they will not have to be lined",""" [MASK] data summary went on to describe the process by which the lagoons could be constructed: The [MASK] attractive aspect [MASK] constructing the lagoons in the lower clay zone of the bluff is that they will not have to be lined"
24,"Also, native materials will not have to be recompacted to form the dikes, as the dikes can be constructed by carving the lagoons out of the bluff and leaving the clay intact around them","Also, native materials will not have to [MASK] recompacted to form the dikes, as the dikes can be constructed by [MASK] the lagoons out [MASK] the bluff and leaving the clay intact around them"
25,Construction concerns for this configuration are primarily slope protection against seepage and removal and disposal of the excavated material,Construction concerns for this configuration are primarily slope protection against seepage and removal and disposal of the excavated material
26,A set of contract documents was sent to NCI,A set of contract [MASK] was sent to NCI
27,"On April 1,1987, bids were opened and NCI was declared the low bidder at $2,059,-991","On April 1,1987, bids were opened and NCI was declared the low bidder at $2,059,-991"
28,"NCI began the excavation on June 6, 1987","NCI began the excavation on June 6, 1987"
29,"Excavation of the first dig, down to the forty-seven foot elevation of the pond surface, was completed","[MASK] of the first dig, down [MASK] the forty-seven foot elevation [MASK] [MASK] [MASK] surface, was completed"
30,Work was suspended in October 1987,Work was suspended in October 1987
31,"The second dig, excavation of the pond prisms, began when the ground froze","The second dig, excavation of the pond prisms, began when [MASK] ground froze"
32,"Excavation was completed by April 20,1988","Excavation was completed by April 20,1988"
33,"During the summer of 1987, while excavating the first dig, NCI encountered water bubbling through sand lenses in the excavation","During the summer of 1987, [MASK] excavating the first dig, NCI encountered water bubbling through sand lenses in the excavation"
34,"Randy Mattoon, NCI's project superintendent, discussed with Tony Neal, president of NCI, the possibility of the existence of sand lenses impairing the integrity of the lagoon, which would allow sewage to escape","Randy [MASK] NCI's project superintendent, discussed with Tony Neal, president of NCI, the possibility of the [MASK] of sand lenses impairing the integrity of the lagoon, which would allow sewage to escape"
35,"Mattoon also discussed the issue of water permeable sand lenses with Bob Richie, Hill's representative","Mattoon also discussed the issue of water permeable sand lenses with [MASK] Richie, Hill's [MASK]"
36,"Ken Green, a Hill geotechnical engineer, was scheduled to visit the project the week of July 27,1987","Ken Green, a Hill geotechnical engineer, was scheduled [MASK] visit the project the week of July 27,1987"
37,NCI contends that Green's visit was scheduled after and because of the Mattoon-Riehie conversation regarding the sand lenses,NCI contends that Green's visit was scheduled [MASK] and because of the Mattoon-Riehie conversation regarding the [MASK] lenses
38,The City and Hill contend that Green's visit had already been scheduled,The [MASK] and Hill contend that Green's visit had [MASK] been scheduled
39,"During Green's visit, a test pit was dug in each of the pond prisms, and a soil sample was taken from one of the pits","[MASK] Green's visit, a test pit was dug in each [MASK] the [MASK] prisms, and [MASK] [MASK] sample was taken from one of the pits"
40,"Green's field notes, taken at the time the pits were dug, indicate that at the level where the lagoons were to be dug, he saw ""clayey silt Slightly plastic Blue Gray Moist slightly Blocky structure, stiff to n","Green's field notes, taken at the time the pits were dug, indicate that at the level where the lagoons were to be dug, he saw ""clayey silt Slightly plastic Blue Gray Moist slightly Blocky structure, stiff to [MASK]"
41,stiff[,stiff[
42,"]"" This level (two to nineteen feet down from the forty-seven foot elevation of the surface of the lagoon) had been described in the Data Summary as ""a layer of stiff-to-hard clay having low-to-medium plasticity","[MASK] This level (two to [MASK] feet down from the forty-seven foot elevation of the [MASK] of the lagoon) had been described in the Data [MASK] [MASK] ""a layer of stiff-to-hard clay [MASK] low-to-medium plasticity"
43,"""\nDuring this time, the consistency of the soil was causing difficulties in NCI's excavation",""" During this time, the consistency [MASK] [MASK] [MASK] was causing difficulties in NCI's excavation"
44,"The soil in the lagoon area turned into a sticky mud, creating problems with excavation and transportation","[MASK] soil in the lagoon area turned into a sticky mud, creating problems with excavation and transportation"
45,"The consistency of the soil, and the difficulty of excavating it, form the basis of NCI's Differing Site Condition claim","[MASK] consistency of the soil, and the difficulty of excavating it, form the [MASK] of NCI's Differing Site [MASK] claim"
46,"During the 1988 phase of the excavation, water infiltration continued to cause problems","During the 1988 phase of [MASK] excavation, water infiltration continued to cause [MASK]"
47,"In October 1988, NCI advised Hill that it was considering legal action","In [MASK] 1988, [MASK] advised Hill that it was considering legal action"
48,NCI then filed suit,NCI then filed [MASK]
49,III,III

In [ ]:
import pandas as pd
from transformers import pipeline, BertTokenizer, BertModel
import torch
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

In [ ]:
# Load the fill-mask pipeline and BERT model
fill_mask = pipeline("fill-mask", model="bert-base-uncased")
tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")
model = BertModel.from_pretrained("bert-base-uncased")

Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertForMaskedLM: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight', 'cls.seq_relationship.bias', 'cls.seq_relationship.weight']
- This IS expected if you are initializing BertForMaskedLM from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForMaskedLM from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Device set to use cpu

In [ ]:
from transformers import BertTokenizer, BertModel
import torch

# Function to calculate sentence embeddings from BERT
def get_bert_embedding(sentence):
    # Load pre-trained BERT model and tokenizer
    tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
    model = BertModel.from_pretrained('bert-base-uncased')  # Ensure you use BertModel, not BertForMaskedLM

    # Tokenize the input sentence
    inputs = tokenizer(sentence, return_tensors='pt', padding=True, truncation=True)

    # Get BERT model outputs (last hidden state)
    with torch.no_grad():  # Disable gradient calculation for efficiency
        outputs = model(**inputs)

    # Get the embeddings of the [CLS] token (first token) as the sentence embedding
    cls_embedding = outputs.last_hidden_state[:, 0, :]

    return cls_embedding

In [ ]:
# Function to compute semantic similarity between two sentences
def get_semantic_similarity(original_text, filled_text):
    original_embedding = get_bert_embedding(original_text)
    filled_embedding = get_bert_embedding(filled_text)

    # Compute cosine similarity between the two embeddings
    similarity = cosine_similarity(original_embedding.numpy(), filled_embedding.numpy())[0][0]
    return similarity

In [ ]:
df_sentences = df_sentences.head(100)

In [ ]:
from transformers import AutoTokenizer, AutoModelForMaskedLM
import torch
import pandas as pd
from tqdm import tqdm

# Initialize tqdm for pandas
tqdm.pandas()

# Define the model name
model_name = "bert-base-uncased"  # You can replace this with other models like roberta-base, etc.

# Load pre-trained model and tokenizer
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForMaskedLM.from_pretrained(model_name)

# Function to fill masked sentences
def predict_masked_sentence(masked_sentence):
    # Tokenize input text
    inputs = tokenizer(masked_sentence, return_tensors="pt")

    # Find masked token positions
    mask_token_index = torch.where(inputs.input_ids == tokenizer.mask_token_id)[1]

    # Forward pass to get predictions
    with torch.no_grad():
        logits = model(**inputs).logits

    # Decode the predictions for the masked tokens
    predicted_tokens = []
    for mask_index in mask_token_index:
        predicted_token_id = logits[0, mask_index].argmax(axis=-1)  # Get the most likely token
        predicted_token = tokenizer.decode(predicted_token_id)
        predicted_tokens.append(predicted_token)

    # Replace the masked tokens with the predicted tokens
    filled_text = masked_sentence
    for mask_token, predicted_token in zip(mask_token_index, predicted_tokens):
        filled_text = filled_text.replace("[MASK]", predicted_token, 1)

    return filled_text

# Assuming df_sentences is your DataFrame with shape (1000, 1)
# Apply the prediction function with tqdm progress bar
df_sentences['predicted_sentences'] = df_sentences['masked_sentences'].progress_apply(predict_masked_sentence)

# Now df_sentences contains a new column 'predicted_sentences' with the predicted masked sentences

Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertForMaskedLM: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight', 'cls.seq_relationship.bias', 'cls.seq_relationship.weight']
- This IS expected if you are initializing BertForMaskedLM from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForMaskedLM from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
100%|██████████| 100/100 [00:18<00:00,  5.34it/s]

In [ ]:
df_sentences

,sentence,masked_sentences,predicted_sentences
0,"OPINION\nRABINOWITZ, Justice",OPINION [MASK] [MASK],OPINION polls .
1,I,I,I
2,"INTRODUCTION\nThis appeal centers on the application of the notice requirement of the Differing Site Conditions clause found in a contract between appellant Neal & Company, Inc","INTRODUCTION This appeal centers on the application of the notice requirement of the [MASK] Site [MASK] clause found in a contract [MASK] appellant Neal & Company, Inc","INTRODUCTION This appeal centers on the application of the notice requirement of the "" Site "" clause found in a contract between appellant Neal & Company, Inc"
3,(NCI) and appellee City of Dillingham (City),(NCI) and appellee City of Dillingham (City),(NCI) and appellee City of Dillingham (City)
4,"Ap-pellee CH2M Hill (Hill), the City's engineer on the project, is involved in this appeal primarily because it acted as the City's representative on the project","Ap-pellee CH2M Hill (Hill), the City's engineer on the project, [MASK] involved in this appeal primarily because it [MASK] as the City's representative on [MASK] project","Ap-pellee CH2M Hill (Hill), the City's engineer on the project, was involved in this appeal primarily because it served as the City's representative on the project"
5,"NCI claims that it encountered difficulties in excavation during the project because of unexpected soil conditions, that it gave notice of these unexpected conditions to Hill (and thus constructively to the City), and that therefore it is entitled to assert a claim under the Differing Site Conditions clause","NCI claims [MASK] it encountered difficulties in excavation [MASK] the project because of unexpected soil conditions, that it gave notice of these [MASK] conditions to Hill [MASK] thus constructively to the City), and that therefore it is entitled to assert a [MASK] under the [MASK] Site Conditions clause","NCI claims that it encountered difficulties in excavation of the project because of unexpected soil conditions, that it gave notice of these soil conditions to Hill ( thus constructively to the City), and that therefore it is entitled to assert a claim under the appropriate Site Conditions clause"
6,The City and Hill claim that no notice of a differing site condition was given,The [MASK] [MASK] Hill claim that no notice of a differing site condition was given,The nearby and Hill claim that no notice of a differing site condition was given
7,The superior court ruled on partial summary judgment that NCI did not give adequate notice of a differing site condition,The superior court ruled on partial summary judgment that NCI did not give adequate notice of a differing site condition,The superior court ruled on partial summary judgment that NCI did not give adequate notice of a differing site condition
8,"NCI also appeals the superior court's denial of its motions for leave to amend its complaint, for continuance of the trial, and for disqualification of thé trial judge","NCI also appeals the superior court's denial of its motions for leave to amend its complaint, for continuance of the trial, and for disqualification of thé trial judge","NCI also appeals the superior court's denial of its motions for leave to amend its complaint, for continuance of the trial, and for disqualification of thé trial judge"
9,II,II,II
10,FACTS\nIn February 1987 the City solicited bids for the construction of a sewerage facility,FACTS In February [MASK] the [MASK] solicited bids for the construction of a sewerage facility,"FACTS In February , the city solicited bids for the construction of a sewerage facility"
11,The project included two lagoon ponds,[MASK] project included two lagoon ponds,the project included two lagoon ponds
12,The lagoons were to be dug into a bluff outside of Dillingham,The lagoons were to be dug into a bluff outside of Dillingham,The lagoons were to be dug into a bluff outside of Dillingham
13,"Interested bidders received a set of drawings and a volume containing bidding requirements, contract forms, conditions of the contract, and construction specifications, along with a ""Geotechnical Data Summary","Interested [MASK] received a set of drawings [MASK] a volume containing bidding requirements, contract forms, conditions of the contract, and construction specifications, along with a ""Geotechnical Data Summary","Interested parties received a set of drawings in a volume containing bidding requirements, contract forms, conditions of the contract, and construction specifications, along with a ""Geotechnical Data Summary"
14,""" The geological survey and the data summary, as well as all technical specifications for the project, were completed by Hill, the City's engineer and on-site representative for the project",""" The geological survey and the [MASK] summary, as well as all technical [MASK] for the project, were completed by [MASK] the [MASK] engineer and on-site representative for the project",""" The geological survey and the technical summary, as well as all technical details for the project, were completed by consulting the chief engineer and on-site representative for the project"
15,The first dig in the construction of the lagoons was to be a wedge-cut into the bluff from the surface down to an elevation of forty-seven feet,[MASK] first dig in the construction of the [MASK] [MASK] to [MASK] a wedge-cut into the bluff from the [MASK] down to an elevation [MASK] forty-seven feet,the first dig in the construction of the fort was to create a wedge-cut into the bluff from the bottom down to an elevation of forty-seven feet
16,"After the first dig down to the forty-seven foot level, the second dig would begin, consisting of the excavation of two ponds down from the flat area created by the first dig","After the first dig down to the forty-seven foot level, the second dig would begin, consisting of the excavation of [MASK] ponds down from the flat [MASK] created by [MASK] [MASK] dig","After the first dig down to the forty-seven foot level, the second dig would begin, consisting of the excavation of two ponds down from the flat level created by the the dig"
17,"The pools were to be eighteen feet deep, reaching an elevation of twenty-nine feet at their lowest point","The pools [MASK] to be [MASK] feet deep, reaching [MASK] elevation of twenty-nine feet at their lowest point","The pools were to be twenty feet deep, reaching an elevation of twenty-nine feet at their lowest point"
18,The data summary stated that there was a layer of peat containing some silt infilling extending four feet to eight feet below the original ground surface,The data summary [MASK] [MASK] there was a layer of [MASK] containing some silt infilling extending four feet to eight [MASK] below the original ground surface,The data summary stated that there was a layer of soil containing some silt infilling extending four feet to eight feet below the original ground surface
19,Below the peat was a layer of sand and silty sand interbedded with layers of silt extending about six to twelve feet below the peat zone,Below [MASK] peat was a layer of sand [MASK] silty sand [MASK] with layers of silt extending about six to twelve feet below the peat zone,"Below the peat was a layer of sand , silty sand , with layers of silt extending about six to twelve feet below the peat zone"
20,"Below that, the data summary described the remaining depth of the excavation as ""fairly uniform to the remaining depth of the borings, showing a layer of stiff-to-hard clay having low-to-medium plasticity","Below that, [MASK] data summary described the remaining depth of the excavation as ""fairly uniform to the remaining depth of the [MASK] showing a layer of stiff-to-hard clay having low-to-medium plasticity","Below that, the data summary described the remaining depth of the excavation as ""fairly uniform to the remaining depth of the excavation showing a layer of stiff-to-hard clay having low-to-medium plasticity"
21,""" Regarding the clay layer, the data summary specified: ""Occasional samples contained clay with gravel and sand suspended in the clay matrix, indicating that the clay unit may be a glacial till",""" [MASK] the clay layer, the data summary specified: [MASK] samples contained clay with gravel and sand suspended in the clay matrix, indicating that the clay unit may be a glacial till",""" for the clay layer, the data summary specified: the samples contained clay with gravel and sand suspended in the clay matrix, indicating that the clay unit may be a glacial till"
22,No distinct bedding or layers of coarse grained material were found in the clay unit,No distinct bedding or layers of coarse grained material [MASK] found in the clay unit,No distinct bedding or layers of coarse grained material were found in the clay unit
23,""" The data summary went on to describe the process by which the lagoons could be constructed:\nThe most attractive aspect of constructing the lagoons in the lower clay zone of the bluff is that they will not have to be lined",""" [MASK] data summary went on to describe the process by which the lagoons could be constructed: The [MASK] attractive aspect [MASK] constructing the lagoons in the lower clay zone of the bluff is that they will not have to be lined",""" the data summary went on to describe the process by which the lagoons could be constructed: The most attractive aspect of constructing the lagoons in the lower clay zone of the bluff is that they will not have to be lined"
24,"Also, native materials will not have to be recompacted to form the dikes, as the dikes can be constructed by carving the lagoons out of the bluff and leaving the clay intact around them","Also, native materials will not have to [MASK] recompacted to form the dikes, as the dikes can be constructed by [MASK] the lagoons out [MASK] the bluff and leaving the clay intact around them","Also, native materials will not have to be recompacted to form the dikes, as the dikes can be constructed by digging the lagoons out of the bluff and leaving the clay intact around them"
25,Construction concerns for this configuration are primarily slope protection against seepage and removal and disposal of the excavated material,Construction concerns for this configuration are primarily slope protection against seepage and removal and disposal of the excavated material,Construction concerns for this configuration are primarily slope protection against seepage and removal and disposal of the excavated material
26,A set of contract documents was sent to NCI,A set of contract [MASK] was sent to NCI,A set of contract documents was sent to NCI
27,"On April 1,1987, bids were opened and NCI was declared the low bidder at $2,059,-991","On April 1,1987, bids were opened and NCI was declared the low bidder at $2,059,-991","On April 1,1987, bids were opened and NCI was declared the low bidder at $2,059,-991"
28,"NCI began the excavation on June 6, 1987","NCI began the excavation on June 6, 1987","NCI began the excavation on June 6, 1987"
29,"Excavation of the first dig, down to the forty-seven foot elevation of the pond surface, was completed","[MASK] of the first dig, down [MASK] the forty-seven foot elevation [MASK] [MASK] [MASK] surface, was completed","construction of the first dig, down to the forty-seven foot elevation of the the surface, was completed"
30,Work was suspended in October 1987,Work was suspended in October 1987,Work was suspended in October 1987
31,"The second dig, excavation of the pond prisms, began when the ground froze","The second dig, excavation of the pond prisms, began when [MASK] ground froze","The second dig, excavation of the pond prisms, began when the ground froze"
32,"Excavation was completed by April 20,1988","Excavation was completed by April 20,1988","Excavation was completed by April 20,1988"
33,"During the summer of 1987, while excavating the first dig, NCI encountered water bubbling through sand lenses in the excavation","During the summer of 1987, [MASK] excavating the first dig, NCI encountered water bubbling through sand lenses in the excavation","During the summer of 1987, while excavating the first dig, NCI encountered water bubbling through sand lenses in the excavation"
34,"Randy Mattoon, NCI's project superintendent, discussed with Tony Neal, president of NCI, the possibility of the existence of sand lenses impairing the integrity of the lagoon, which would allow sewage to escape","Randy [MASK] NCI's project superintendent, discussed with Tony Neal, president of NCI, the possibility of the [MASK] of sand lenses impairing the integrity of the lagoon, which would allow sewage to escape","Randy , NCI's project superintendent, discussed with Tony Neal, president of NCI, the possibility of the use of sand lenses impairing the integrity of the lagoon, which would allow sewage to escape"
35,"Mattoon also discussed the issue of water permeable sand lenses with Bob Richie, Hill's representative","Mattoon also discussed the issue of water permeable sand lenses with [MASK] Richie, Hill's [MASK]","Mattoon also discussed the issue of water permeable sand lenses with lionel Richie, Hill's ."
36,"Ken Green, a Hill geotechnical engineer, was scheduled to visit the project the week of July 27,1987","Ken Green, a Hill geotechnical engineer, was scheduled [MASK] visit the project the week of July 27,1987","Ken Green, a Hill geotechnical engineer, was scheduled to visit the project the week of July 27,1987"
37,NCI contends that Green's visit was scheduled after and because of the Mattoon-Riehie conversation regarding the sand lenses,NCI contends that Green's visit was scheduled [MASK] and because of the Mattoon-Riehie conversation regarding the [MASK] lenses,"NCI contends that Green's visit was scheduled , and because of the Mattoon-Riehie conversation regarding the contact lenses"
38,The City and Hill contend that Green's visit had already been scheduled,The [MASK] and Hill contend that Green's visit had [MASK] been scheduled,The judge and Hill contend that Green's visit had not been scheduled
39,"During Green's visit, a test pit was dug in each of the pond prisms, and a soil sample was taken from one of the pits","[MASK] Green's visit, a test pit was dug in each [MASK] the [MASK] prisms, and [MASK] [MASK] sample was taken from one of the pits","during Green's visit, a test pit was dug in each of the three prisms, and a a sample was taken from one of the pits"
40,"Green's field notes, taken at the time the pits were dug, indicate that at the level where the lagoons were to be dug, he saw ""clayey silt Slightly plastic Blue Gray Moist slightly Blocky structure, stiff to n","Green's field notes, taken at the time the pits were dug, indicate that at the level where the lagoons were to be dug, he saw ""clayey silt Slightly plastic Blue Gray Moist slightly Blocky structure, stiff to [MASK]","Green's field notes, taken at the time the pits were dug, indicate that at the level where the lagoons were to be dug, he saw ""clayey silt Slightly plastic Blue Gray Moist slightly Blocky structure, stiff to ."
41,stiff[,stiff[,stiff[
42,"]"" This level (two to nineteen feet down from the forty-seven foot elevation of the surface of the lagoon) had been described in the Data Summary as ""a layer of stiff-to-hard clay having low-to-medium plasticity","[MASK] This level (two to [MASK] feet down from the forty-seven foot elevation of the [MASK] of the lagoon) had been described in the Data [MASK] [MASK] ""a layer of stiff-to-hard clay [MASK] low-to-medium plasticity",""" This level (two to three feet down from the forty-seven foot elevation of the mouth of the lagoon) had been described in the Data as as ""a layer of stiff-to-hard clay and low-to-medium plasticity"
43,"""\nDuring this time, the consistency of the soil was causing difficulties in NCI's excavation",""" During this time, the consistency [MASK] [MASK] [MASK] was causing difficulties in NCI's excavation",""" During this time, the consistency of of data was causing difficulties in NCI's excavation"
44,"The soil in the lagoon area turned into a sticky mud, creating problems with excavation and transportation","[MASK] soil in the lagoon area turned into a sticky mud, creating problems with excavation and transportation","the soil in the lagoon area turned into a sticky mud, creating problems with excavation and transportation"
45,"The consistency of the soil, and the difficulty of excavating it, form the basis of NCI's Differing Site Condition claim","[MASK] consistency of the soil, and the difficulty of excavating it, form the [MASK] of NCI's Differing Site [MASK] claim","the consistency of the soil, and the difficulty of excavating it, form the basis of NCI's Differing Site requirements claim"
46,"During the 1988 phase of the excavation, water infiltration continued to cause problems","During the 1988 phase of [MASK] excavation, water infiltration continued to cause [MASK]","During the 1988 phase of the excavation, water infiltration continued to cause ."
47,"In October 1988, NCI advised Hill that it was considering legal action","In [MASK] 1988, [MASK] advised Hill that it was considering legal action","In january 1988, ford advised Hill that it was considering legal action"
48,NCI then filed suit,NCI then filed [MASK],NCI then filed .
49,III,III,III
50,SUPERIOR COURT PROCEEDINGS,SUPERIOR COURT PROCEEDINGS,SUPERIOR COURT PROCEEDINGS
51,"During the course of these proceedings, numerous claims and cross-claims were filed","During [MASK] course [MASK] these proceedings, numerous claims and cross-claims were filed","During the course of these proceedings, numerous claims and cross-claims were filed"
52,The following are relevant to this appeal,The following are relevant to this appeal,The following are relevant to this appeal
53,"On March 29, 1990, NCI filed a second amended complaint, which added NCI's Differing Site Condition claim to the lawsuit as the sixth cause of action, and added what NCI interprets as a defective specifications claim as the seventh cause of action","On March 29, [MASK] NCI filed a second amended complaint, [MASK] [MASK] NCI's [MASK] Site Condition claim [MASK] the lawsuit as the sixth [MASK] of action, and added what NCI interprets as a [MASK] specifications claim as the seventh [MASK] of [MASK]","On March 29, 2016 NCI filed a second amended complaint, which removed NCI's web Site Condition claim in the lawsuit as the sixth cause of action, and added what NCI interprets as a technical specifications claim as the seventh cause of ."
54,"In May, NCI filed a substitute second amended complaint","In May, NCI filed a substitute second amended [MASK]","In May, NCI filed a substitute second amended ."
55,"Judge Beverly Cutler granted the motion to amend on August 6, 1990","Judge Beverly Cutler granted the motion to amend on August 6, 1990","Judge Beverly Cutler granted the motion to amend on August 6, 1990"
56,"In January 1991, the City, seeking indemnity from NCI's claims, filed a third-party complaint against Hill","In January 1991, the City, [MASK] indemnity from NCI's claims, filed a third-party complaint against [MASK]","In January 1991, the City, seeking indemnity from NCI's claims, filed a third-party complaint against ."
57,"In November 1991, Hill filed a motion for partial summary judgment based on the limitation of liability and indemnity clause in its contract with the City","In November 1991, Hill filed a motion for partial summary [MASK] based on the limitation [MASK] liability and indemnity clause in its contract with [MASK] City","In November 1991, Hill filed a motion for partial summary judgment based on the limitation of liability and indemnity clause in its contract with the City"
58,The superior court ruled for Hill,The superior court ruled for Hill,The superior court ruled for Hill

In [ ]:
v1 = "big dog"
v2 = "big cat"
print(get_semantic_similarity(v1, v2))
df_sentences['semantic similarity'] = df_sentences.progress_apply(
    lambda row: get_semantic_similarity(row['predicted_sentences'], row['sentence']), axis=1
)

0.9618647

100%|██████████| 100/100 [02:01<00:00,  1.21s/it]

In [ ]:
df_sentences.head(100)

,sentence,masked_sentences,predicted_sentences,semantic similarity
0,"OPINION\nRABINOWITZ, Justice",OPINION [MASK] [MASK],OPINION polls .,0.684500
1,I,I,I,1.000000
2,"INTRODUCTION\nThis appeal centers on the application of the notice requirement of the Differing Site Conditions clause found in a contract between appellant Neal & Company, Inc","INTRODUCTION This appeal centers on the application of the notice requirement of the [MASK] Site [MASK] clause found in a contract [MASK] appellant Neal & Company, Inc","INTRODUCTION This appeal centers on the application of the notice requirement of the "" Site "" clause found in a contract between appellant Neal & Company, Inc",0.996927
3,(NCI) and appellee City of Dillingham (City),(NCI) and appellee City of Dillingham (City),(NCI) and appellee City of Dillingham (City),1.000000
4,"Ap-pellee CH2M Hill (Hill), the City's engineer on the project, is involved in this appeal primarily because it acted as the City's representative on the project","Ap-pellee CH2M Hill (Hill), the City's engineer on the project, [MASK] involved in this appeal primarily because it [MASK] as the City's representative on [MASK] project","Ap-pellee CH2M Hill (Hill), the City's engineer on the project, was involved in this appeal primarily because it served as the City's representative on the project",0.984452
5,"NCI claims that it encountered difficulties in excavation during the project because of unexpected soil conditions, that it gave notice of these unexpected conditions to Hill (and thus constructively to the City), and that therefore it is entitled to assert a claim under the Differing Site Conditions clause","NCI claims [MASK] it encountered difficulties in excavation [MASK] the project because of unexpected soil conditions, that it gave notice of these [MASK] conditions to Hill [MASK] thus constructively to the City), and that therefore it is entitled to assert a [MASK] under the [MASK] Site Conditions clause","NCI claims that it encountered difficulties in excavation of the project because of unexpected soil conditions, that it gave notice of these soil conditions to Hill ( thus constructively to the City), and that therefore it is entitled to assert a claim under the appropriate Site Conditions clause",0.991062
6,The City and Hill claim that no notice of a differing site condition was given,The [MASK] [MASK] Hill claim that no notice of a differing site condition was given,The nearby and Hill claim that no notice of a differing site condition was given,0.965059
7,The superior court ruled on partial summary judgment that NCI did not give adequate notice of a differing site condition,The superior court ruled on partial summary judgment that NCI did not give adequate notice of a differing site condition,The superior court ruled on partial summary judgment that NCI did not give adequate notice of a differing site condition,1.000000
8,"NCI also appeals the superior court's denial of its motions for leave to amend its complaint, for continuance of the trial, and for disqualification of thé trial judge","NCI also appeals the superior court's denial of its motions for leave to amend its complaint, for continuance of the trial, and for disqualification of thé trial judge","NCI also appeals the superior court's denial of its motions for leave to amend its complaint, for continuance of the trial, and for disqualification of thé trial judge",1.000000
9,II,II,II,1.000000
10,FACTS\nIn February 1987 the City solicited bids for the construction of a sewerage facility,FACTS In February [MASK] the [MASK] solicited bids for the construction of a sewerage facility,"FACTS In February , the city solicited bids for the construction of a sewerage facility",0.937577
11,The project included two lagoon ponds,[MASK] project included two lagoon ponds,the project included two lagoon ponds,1.000000
12,The lagoons were to be dug into a bluff outside of Dillingham,The lagoons were to be dug into a bluff outside of Dillingham,The lagoons were to be dug into a bluff outside of Dillingham,1.000000
13,"Interested bidders received a set of drawings and a volume containing bidding requirements, contract forms, conditions of the contract, and construction specifications, along with a ""Geotechnical Data Summary","Interested [MASK] received a set of drawings [MASK] a volume containing bidding requirements, contract forms, conditions of the contract, and construction specifications, along with a ""Geotechnical Data Summary","Interested parties received a set of drawings in a volume containing bidding requirements, contract forms, conditions of the contract, and construction specifications, along with a ""Geotechnical Data Summary",0.995921
14,""" The geological survey and the data summary, as well as all technical specifications for the project, were completed by Hill, the City's engineer and on-site representative for the project",""" The geological survey and the [MASK] summary, as well as all technical [MASK] for the project, were completed by [MASK] the [MASK] engineer and on-site representative for the project",""" The geological survey and the technical summary, as well as all technical details for the project, were completed by consulting the chief engineer and on-site representative for the project",0.950305
15,The first dig in the construction of the lagoons was to be a wedge-cut into the bluff from the surface down to an elevation of forty-seven feet,[MASK] first dig in the construction of the [MASK] [MASK] to [MASK] a wedge-cut into the bluff from the [MASK] down to an elevation [MASK] forty-seven feet,the first dig in the construction of the fort was to create a wedge-cut into the bluff from the bottom down to an elevation of forty-seven feet,0.967240
16,"After the first dig down to the forty-seven foot level, the second dig would begin, consisting of the excavation of two ponds down from the flat area created by the first dig","After the first dig down to the forty-seven foot level, the second dig would begin, consisting of the excavation of [MASK] ponds down from the flat [MASK] created by [MASK] [MASK] dig","After the first dig down to the forty-seven foot level, the second dig would begin, consisting of the excavation of two ponds down from the flat level created by the the dig",0.986780
17,"The pools were to be eighteen feet deep, reaching an elevation of twenty-nine feet at their lowest point","The pools [MASK] to be [MASK] feet deep, reaching [MASK] elevation of twenty-nine feet at their lowest point","The pools were to be twenty feet deep, reaching an elevation of twenty-nine feet at their lowest point",0.999543
18,The data summary stated that there was a layer of peat containing some silt infilling extending four feet to eight feet below the original ground surface,The data summary [MASK] [MASK] there was a layer of [MASK] containing some silt infilling extending four feet to eight [MASK] below the original ground surface,The data summary stated that there was a layer of soil containing some silt infilling extending four feet to eight feet below the original ground surface,0.981707
19,Below the peat was a layer of sand and silty sand interbedded with layers of silt extending about six to twelve feet below the peat zone,Below [MASK] peat was a layer of sand [MASK] silty sand [MASK] with layers of silt extending about six to twelve feet below the peat zone,"Below the peat was a layer of sand , silty sand , with layers of silt extending about six to twelve feet below the peat zone",0.979341
20,"Below that, the data summary described the remaining depth of the excavation as ""fairly uniform to the remaining depth of the borings, showing a layer of stiff-to-hard clay having low-to-medium plasticity","Below that, [MASK] data summary described the remaining depth of the excavation as ""fairly uniform to the remaining depth of the [MASK] showing a layer of stiff-to-hard clay having low-to-medium plasticity","Below that, the data summary described the remaining depth of the excavation as ""fairly uniform to the remaining depth of the excavation showing a layer of stiff-to-hard clay having low-to-medium plasticity",0.988506
21,""" Regarding the clay layer, the data summary specified: ""Occasional samples contained clay with gravel and sand suspended in the clay matrix, indicating that the clay unit may be a glacial till",""" [MASK] the clay layer, the data summary specified: [MASK] samples contained clay with gravel and sand suspended in the clay matrix, indicating that the clay unit may be a glacial till",""" for the clay layer, the data summary specified: the samples contained clay with gravel and sand suspended in the clay matrix, indicating that the clay unit may be a glacial till",0.976573
22,No distinct bedding or layers of coarse grained material were found in the clay unit,No distinct bedding or layers of coarse grained material [MASK] found in the clay unit,No distinct bedding or layers of coarse grained material were found in the clay unit,1.000000
23,""" The data summary went on to describe the process by which the lagoons could be constructed:\nThe most attractive aspect of constructing the lagoons in the lower clay zone of the bluff is that they will not have to be lined",""" [MASK] data summary went on to describe the process by which the lagoons could be constructed: The [MASK] attractive aspect [MASK] constructing the lagoons in the lower clay zone of the bluff is that they will not have to be lined",""" the data summary went on to describe the process by which the lagoons could be constructed: The most attractive aspect of constructing the lagoons in the lower clay zone of the bluff is that they will not have to be lined",1.000000
24,"Also, native materials will not have to be recompacted to form the dikes, as the dikes can be constructed by carving the lagoons out of the bluff and leaving the clay intact around them","Also, native materials will not have to [MASK] recompacted to form the dikes, as the dikes can be constructed by [MASK] the lagoons out [MASK] the bluff and leaving the clay intact around them","Also, native materials will not have to be recompacted to form the dikes, as the dikes can be constructed by digging the lagoons out of the bluff and leaving the clay intact around them",0.998237
25,Construction concerns for this configuration are primarily slope protection against seepage and removal and disposal of the excavated material,Construction concerns for this configuration are primarily slope protection against seepage and removal and disposal of the excavated material,Construction concerns for this configuration are primarily slope protection against seepage and removal and disposal of the excavated material,1.000000
26,A set of contract documents was sent to NCI,A set of contract [MASK] was sent to NCI,A set of contract documents was sent to NCI,1.000000
27,"On April 1,1987, bids were opened and NCI was declared the low bidder at $2,059,-991","On April 1,1987, bids were opened and NCI was declared the low bidder at $2,059,-991","On April 1,1987, bids were opened and NCI was declared the low bidder at $2,059,-991",1.000000
28,"NCI began the excavation on June 6, 1987","NCI began the excavation on June 6, 1987","NCI began the excavation on June 6, 1987",1.000000
29,"Excavation of the first dig, down to the forty-seven foot elevation of the pond surface, was completed","[MASK] of the first dig, down [MASK] the forty-seven foot elevation [MASK] [MASK] [MASK] surface, was completed","construction of the first dig, down to the forty-seven foot elevation of the the surface, was completed",0.964505
30,Work was suspended in October 1987,Work was suspended in October 1987,Work was suspended in October 1987,1.000000
31,"The second dig, excavation of the pond prisms, began when the ground froze","The second dig, excavation of the pond prisms, began when [MASK] ground froze","The second dig, excavation of the pond prisms, began when the ground froze",1.000000
32,"Excavation was completed by April 20,1988","Excavation was completed by April 20,1988","Excavation was completed by April 20,1988",1.000000
33,"During the summer of 1987, while excavating the first dig, NCI encountered water bubbling through sand lenses in the excavation","During the summer of 1987, [MASK] excavating the first dig, NCI encountered water bubbling through sand lenses in the excavation","During the summer of 1987, while excavating the first dig, NCI encountered water bubbling through sand lenses in the excavation",1.000000
34,"Randy Mattoon, NCI's project superintendent, discussed with Tony Neal, president of NCI, the possibility of the existence of sand lenses impairing the integrity of the lagoon, which would allow sewage to escape","Randy [MASK] NCI's project superintendent, discussed with Tony Neal, president of NCI, the possibility of the [MASK] of sand lenses impairing the integrity of the lagoon, which would allow sewage to escape","Randy , NCI's project superintendent, discussed with Tony Neal, president of NCI, the possibility of the use of sand lenses impairing the integrity of the lagoon, which would allow sewage to escape",0.989509
35,"Mattoon also discussed the issue of water permeable sand lenses with Bob Richie, Hill's representative","Mattoon also discussed the issue of water permeable sand lenses with [MASK] Richie, Hill's [MASK]","Mattoon also discussed the issue of water permeable sand lenses with lionel Richie, Hill's .",0.934656
36,"Ken Green, a Hill geotechnical engineer, was scheduled to visit the project the week of July 27,1987","Ken Green, a Hill geotechnical engineer, was scheduled [MASK] visit the project the week of July 27,1987","Ken Green, a Hill geotechnical engineer, was scheduled to visit the project the week of July 27,1987",1.000000
37,NCI contends that Green's visit was scheduled after and because of the Mattoon-Riehie conversation regarding the sand lenses,NCI contends that Green's visit was scheduled [MASK] and because of the Mattoon-Riehie conversation regarding the [MASK] lenses,"NCI contends that Green's visit was scheduled , and because of the Mattoon-Riehie conversation regarding the contact lenses",0.980920
38,The City and Hill contend that Green's visit had already been scheduled,The [MASK] and Hill contend that Green's visit had [MASK] been scheduled,The judge and Hill contend that Green's visit had not been scheduled,0.956956
39,"During Green's visit, a test pit was dug in each of the pond prisms, and a soil sample was taken from one of the pits","[MASK] Green's visit, a test pit was dug in each [MASK] the [MASK] prisms, and [MASK] [MASK] sample was taken from one of the pits","during Green's visit, a test pit was dug in each of the three prisms, and a a sample was taken from one of the pits",0.951796
40,"Green's field notes, taken at the time the pits were dug, indicate that at the level where the lagoons were to be dug, he saw ""clayey silt Slightly plastic Blue Gray Moist slightly Blocky structure, stiff to n","Green's field notes, taken at the time the pits were dug, indicate that at the level where the lagoons were to be dug, he saw ""clayey silt Slightly plastic Blue Gray Moist slightly Blocky structure, stiff to [MASK]","Green's field notes, taken at the time the pits were dug, indicate that at the level where the lagoons were to be dug, he saw ""clayey silt Slightly plastic Blue Gray Moist slightly Blocky structure, stiff to .",0.940957
41,stiff[,stiff[,stiff[,1.000000
42,"]"" This level (two to nineteen feet down from the forty-seven foot elevation of the surface of the lagoon) had been described in the Data Summary as ""a layer of stiff-to-hard clay having low-to-medium plasticity","[MASK] This level (two to [MASK] feet down from the forty-seven foot elevation of the [MASK] of the lagoon) had been described in the Data [MASK] [MASK] ""a layer of stiff-to-hard clay [MASK] low-to-medium plasticity",""" This level (two to three feet down from the forty-seven foot elevation of the mouth of the lagoon) had been described in the Data as as ""a layer of stiff-to-hard clay and low-to-medium plasticity",0.943099
43,"""\nDuring this time, the consistency of the soil was causing difficulties in NCI's excavation",""" During this time, the consistency [MASK] [MASK] [MASK] was causing difficulties in NCI's excavation",""" During this time, the consistency of of data was causing difficulties in NCI's excavation",0.948804
44,"The soil in the lagoon area turned into a sticky mud, creating problems with excavation and transportation","[MASK] soil in the lagoon area turned into a sticky mud, creating problems with excavation and transportation","the soil in the lagoon area turned into a sticky mud, creating problems with excavation and transportation",1.000000
45,"The consistency of the soil, and the difficulty of excavating it, form the basis of NCI's Differing Site Condition claim","[MASK] consistency of the soil, and the difficulty of excavating it, form the [MASK] of NCI's Differing Site [MASK] claim","the consistency of the soil, and the difficulty of excavating it, form the basis of NCI's Differing Site requirements claim",0.984775
46,"During the 1988 phase of the excavation, water infiltration continued to cause problems","During the 1988 phase of [MASK] excavation, water infiltration continued to cause [MASK]","During the 1988 phase of the excavation, water infiltration continued to cause .",0.970668
47,"In October 1988, NCI advised Hill that it was considering legal action","In [MASK] 1988, [MASK] advised Hill that it was considering legal action","In january 1988, ford advised Hill that it was considering legal action",0.945499
48,NCI then filed suit,NCI then filed [MASK],NCI then filed .,0.944250
49,III,III,III,1.000000
50,SUPERIOR COURT PROCEEDINGS,SUPERIOR COURT PROCEEDINGS,SUPERIOR COURT PROCEEDINGS,1.000000
51,"During the course of these proceedings, numerous claims and cross-claims were filed","During [MASK] course [MASK] these proceedings, numerous claims and cross-claims were filed","During the course of these proceedings, numerous claims and cross-claims were filed",1.000000
52,The following are relevant to this appeal,The following are relevant to this appeal,The following are relevant to this appeal,1.000000
53,"On March 29, 1990, NCI filed a second amended complaint, which added NCI's Differing Site Condition claim to the lawsuit as the sixth cause of action, and added what NCI interprets as a defective specifications claim as the seventh cause of action","On March 29, [MASK] NCI filed a second amended complaint, [MASK] [MASK] NCI's [MASK] Site Condition claim [MASK] the lawsuit as the sixth [MASK] of action, and added what NCI interprets as a [MASK] specifications claim as the seventh [MASK] of [MASK]","On March 29, 2016 NCI filed a second amended complaint, which removed NCI's web Site Condition claim in the lawsuit as the sixth cause of action, and added what NCI interprets as a technical specifications claim as the seventh cause of .",0.951995
54,"In May, NCI filed a substitute second amended complaint","In May, NCI filed a substitute second amended [MASK]","In May, NCI filed a substitute second amended .",0.945769
55,"Judge Beverly Cutler granted the motion to amend on August 6, 1990","Judge Beverly Cutler granted the motion to amend on August 6, 1990","Judge Beverly Cutler granted the motion to amend on August 6, 1990",1.000000
56,"In January 1991, the City, seeking indemnity from NCI's claims, filed a third-party complaint against Hill","In January 1991, the City, [MASK] indemnity from NCI's claims, filed a third-party complaint against [MASK]","In January 1991, the City, seeking indemnity from NCI's claims, filed a third-party complaint against .",0.926699

In [ ]:
df_sentences['semantic similarity'].mean()

0.9793442